---
- name: Install Needed Files
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars_files:
    - build-vars.yml
  tasks:
    - name: Install Pre-Dependencies
      ansible.builtin.apt:
        state: latest
        pkg: 
          - libpq-dev 
          - curl 
          - gnupg
          - git-core 
          - zlib1g-dev 
          - bison
          - build-essential 
          - libssl-dev 
          - libreadline-dev 
          - libyaml-dev 
          - libxml2-dev 
          - libxslt1-dev 
          - libcurl4-openssl-dev 
          - software-properties-common 
          - libffi-dev
          - yarn
    - name: Make dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0555"
      loop:
        - "{{ rbenv.dir }}"
        - /etc/apt/keyrings/
    - name: Setup user bashrc
      ansible.builtin.file:
        src: "/{{ run.user }}/.bashrc"
        line: "{{ item }}"
      loop:
        - "export PATH=\"{{ rbenv.dir }} /bin:$PATH\""
        - eval \"$(rbenv init -)\"
    - name: Git Ruby
      ansible.builtin.git:
        repo: 'https://github.com/rbenv/rbenv.git'
        single_branch: yes
        version: master
        dest: "{{ rbenv.dir }}"
    - name: Create RBENV, Ruby, and Rails install script
      ansible.builtin.template:
        src: "rbenv.j2"
        dest: /usr/local/bin/rails-setup
        mode: "0555"
    - name: De-armor node key
      shell: 
        chdir: /opt
        cmd: |
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - name: Adding node repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro main"
        filename: noderpm     
    - name: Install Node and friends
      ansible.builtin.apt:
        state: latest
        pkg: 
          - nodejs
          - nginx-light