---
- name: Install Needed Files and services
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars_files:
    - build-vars.yml
  tasks:
    - name: Install Pre-Dependencies
      ansible.builtin.apt:
        update_cache: true
        state: latest
        pkg:
          - autoconf
          - bison
          - build-essential
          - curl
          - git-core
          - gnupg
          - libcurl4-openssl-dev
          - libdb-dev
          - libffi-dev
          - libgdbm-dev
          - libgmp-dev
          - libncurses5-dev
          - libpq-dev
          - libssl-dev
          - libxml2-dev
          - libxslt1-dev
          - libyaml-dev
          - nodejs
          - patch
          - postgresql-client
          - rbenv
          - ruby-dev
          - ruby-build
          - rustc
          - software-properties-common
          - uuid-dev
          - yarn
          - zlib1g-dev
    - name: Libraries which depend on version
      block:
        - name: Install GDM6
          ansible.builtin.apt:
            pkg:
              - libgdbm6
              - libreadline6-dev
      rescue:
        - name: Install GDM5
          ansible.builtin.apt:
            pkg:
              - libgdbm5
              - libreadline-dev
    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        createhome: true
      loop:
        - "{{ run.user }}"
    - name: Make dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0555"
      loop:
        - "{{ rbenv.dir }}"
        - /etc/apt/keyrings/
    - name: Setup user bashrc
      become_user: "{{ run.user }}"
      ansible.builtin.lineinfile:
        path: "~/.bashrc"
        line: "{{ item }}"
        create: true
      loop:
        - "export PATH=\"{{ rbenv.dir }} /bin:$PATH\""
        - "eval \"$(rbenv init -)\""
    - name: Git RBENV
      become_user: "{{ run.user }}"
      ansible.builtin.git:
        repo: 'https://github.com/rbenv/rbenv.git'
        single_branch: yes
        version: "v{{ rbenv.version }}"
        dest: "{{ rbenv.dir }}"
    - name: Git RBENV Ruby Build
      become_user: "{{ run.user }}"
      ansible.builtin.git:
        repo: 'https://github.com/rbenv/ruby-build.git'
        single_branch: yes
        version: "v{{ rbenv.buildVersion }}"
        dest: "{{ rbenv.dir }}/plugins/ruby-build"
    - name: Install Ruby 
      become_user: "{{ run.user }}" 
      ansible.builtin.shell:
        cmd: |
          source ~/.bashrc
          rbenv install -l
          rbenv install {{ ruby.version }}
          rbenv global {{ ruby.version }}
    - name: Installl Bundler Gem
      ansible.builtin.shell:
        cmd: |
          gem install bundler
          bundle install 
    - name: Install Raills Gem
      become_user: "{{ run.user }}"
      ansible.builtin.shell:
        cmd: |
          gem install rails -v {{ rails.version }}
          

