---
- name: Install Needed Files and services
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars_files:
    - build-vars.yml
  tasks:
    - name: Install Pre-Dependencies
      ansible.builtin.apt:
        state: latest
        pkg: 
          - bison
          - build-essential
          - curl
          - git-core
          - gnupg
          - libcurl4-openssl-dev
          - libffi-dev
          - libpq-dev
          - libreadline-dev
          - libssl-dev
          - libxml2-dev
          - libxslt1-dev
          - libyaml-dev
          - nodejs
          - postgresql-client
          - rbenv
          - ruby-build
          - software-properties-common
          - yarn
          - zlib1g-dev
    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        createhome: true
      loop:
        - "{{ run.user }}"
    - name: Make dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0555"
      loop:
        - "{{ rbenv.dir }}"
        - /etc/apt/keyrings/
    - name: Setup user bashrc
      ansible.builtin.lineinfile:
        path: "/{{ run.user }}/.bashrc"
        line: "{{ item }}"
        create: true
      loop:
        - "export PATH=\"{{ rbenv.dir }} /bin:$PATH\""
        - "eval \"$(rbenv init -)\""
    - name: Git Ruby
      ansible.builtin.git:
        repo: 'https://github.com/rbenv/rbenv.git'
        single_branch: yes
        version: master
        dest: "{{ rbenv.dir }}"
    - name: Install Ruby Build
      ansible.builtin.shell:
        cmd: |
          rbenv install {{ rbenv.version }}
          rbenv global {{ rbenv.version }}
          gem install bundler
          bundle install rails

